CREATE TABLE `actionLog` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `status` VARCHAR(15) NULL,
    `blank` VARCHAR(50) NULL,
    `date_time` DATETIME NULL,
    `control_number` VARCHAR(150) NULL,
    `reference_number` VARCHAR(150) NULL,
    `payor` VARCHAR(150) NULL,
    `address` VARCHAR(150) NULL,
    `account_number` VARCHAR(150) NULL,
    `account_name` VARCHAR(150) NULL,
    `amount_paid` DECIMAL(15, 2) NULL,
    `charge_to_partner` DECIMAL(15, 2) NULL,
    `charge_to_customer` DECIMAL(15, 2) NULL,
    `contact_number` VARCHAR(25) NULL,
    `other_details` TEXT NULL,
    `ml_outlet` VARCHAR(200) NULL,
    `region` VARCHAR(200) NULL,
    `operator` VARCHAR(250) NULL,
    `partner_name` VARCHAR(250) NULL,
    `partner_id` VARCHAR(150) NULL,
    `imported_date` DATETIME NULL,
    `imported_by` VARCHAR(250) NULL,
    `logged_by` VARCHAR(250) NULL,
    `remark1` TEXT,
    `date1` VARCHAR(150) NULL,
    `remark_by1` VARCHAR(250) NULL,
    `remark2` TEXT,
    `date2` VARCHAR(150) NULL,
    `remark_by2` VARCHAR(250) NULL,
    `remark3` TEXT,
    `date3` VARCHAR(150) NULL,
    `remark_by3` VARCHAR(250) NULL,
    `remark4` TEXT,
    `date4` VARCHAR(150) NULL,
    `remark_by4` VARCHAR(250) NULL,
    `remark5` TEXT,
    `date5` VARCHAR(150) NULL,
    `remark_by5` VARCHAR(250) NULL,
    `remark6` TEXT,
    `date6` VARCHAR(150) NULL,
    `remark_by6` VARCHAR(250) NULL,
    `remark7` TEXT,
    `date7` VARCHAR(150) NULL,
    `remark_by7` VARCHAR(250) NULL,
    `remark8` TEXT,
    `date8` VARCHAR(150) NULL,
    `remark_by8` VARCHAR(250) NULL,
    `remark9` TEXT,
    `date9` VARCHAR(150) NULL,
    `remark_by9` VARCHAR(250) NULL,
    `remark10` TEXT,
    `date10` VARCHAR(150) NULL,
    `remark_by10` VARCHAR(250) NULL,
    `log_status` VARCHAR(100) NULL,
    `logged_date` VARCHAR(100) NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
