CREATE TABLE `billsPayment_others` (
  `id` int NOT NULL AUTO_INCREMENT,
  `status` varchar(15) NOT NULL,
  `blank` varchar(50) NOT NULL,
  `date_time` varchar(150) NOT NULL,
  `control_number` varchar(150) NOT NULL,
  `reference_number` varchar(150) NOT NULL,
  `payor` varchar(150) NOT NULL,
  `address` varchar(150) NOT NULL,
  `account_number` varchar(150) NOT NULL,
  `account_name` varchar(150) NOT NULL,
  `amount_paid` decimal(15,2) NOT NULL,
  `charge_to_partner` decimal(15,2) NOT NULL,
  `charge_to_customer` decimal(15,2) NOT NULL,
  `contact_number` varchar(25) NOT NULL,
  `other_details` varchar(200) NOT NULL,
  `ml_outlet` varchar(200) NOT NULL,
  `region` varchar(200) NOT NULL,
  `operator` varchar(250) NOT NULL,
  `partner_name` varchar(250) NOT NULL,
  `partner_id` varchar(150) NOT NULL,
  `imported_date` datetime NOT NULL,
  `imported_by` varchar(250) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
