CREATE TABLE `temp_billsPayment` (
  `id` int NOT NULL AUTO_INCREMENT,
  `status` varchar(15) NULL,
  `cancellation_date` varchar(150) NULL,
  `date_time` varchar(150) NULL,
  `control_number` varchar(150) NULL,
  `reference_number` varchar(150) NULL,
  `payor` varchar(150) NULL,
  `address` varchar(150) NULL,
  `account_number` varchar(150) NULL,
  `account_name` varchar(150) NULL,
  `amount_paid` decimal(15,2) NULL,
  `charge_to_partner` decimal(15,2) NULL,
  `charge_to_customer` decimal(15,2) NULL,
  `contact_number` char(25) NULL,
  `other_details` varchar(200) NULL,
  `ml_outlet` varchar(200) NULL,
  `region` varchar(200) NULL,
  `operator` varchar(250) NULL,
  `partner_name` varchar(250) NULL,
  `partner_id` varchar(150) NULL,
  `imported_date` datetime NULL,
  `imported_by` varchar(250) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
