<?php
require_once('../vendor/autoload.php'); // Make sure you have TCPDF or similar library
session_start();

if (isset($_SESSION['user_type'])) {
    $current_user_email = '';
    if ($_SESSION['user_type'] === 'admin' && isset($_SESSION['admin_email'])) {
        $current_user_email = $_SESSION['admin_email'];
    } elseif ($_SESSION['user_type'] === 'user' && isset($_SESSION['user_email'])) {
        $current_user_email = $_SESSION['user_email'];
        if($_SESSION['user_email'] === 'balb01013333' || $_SESSION['user_email'] === 'pera94005055'){
            header("Location:../../../index.php");
            session_destroy();
            exit();
        }
    }else{
        header("Location:../../../index.php");
        session_destroy();
        exit();
    }
}

// Get data from POST
$partnerData = json_decode($_POST['partner_data'] ?? '[]', true);
$fileName = $_POST['file_name'] ?? 'Unknown File';
$sourceType = $_POST['source_type'] ?? 'Unknown';
$transactionDate = $_POST['transaction_date'] ?? date('Y-m-d');

// If you're using TCPDF (install via composer: composer require tecnickcom/tcpdf)
require_once('../vendor/tecnickcom/tcpdf/tcpdf.php');

class PartnerErrorPDF extends TCPDF {
    public function Header() {
        // Logo
        $this->SetFont('helvetica', 'B', 16);
        $this->Cell(0, 15, 'Partner Not Found Error Report', 0, 1, 'C');
        $this->Ln(5);
    }
    
    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('helvetica', 'I', 8);
        $this->Cell(0, 10, 'Page ' . $this->getAliasNumPage() . ' of ' . $this->getAliasNbPages(), 0, 0, 'C');
    }
}

// Create new PDF document
$pdf = new PartnerErrorPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('ML Wallet');
$pdf->SetAuthor($_SESSION['admin_name'] ?? 'System');
$pdf->SetTitle('Partner Not Found Error Report');
$pdf->SetSubject('Import Error Report');

// Set margins
$pdf->SetMargins(15, 25, 15);
$pdf->SetHeaderMargin(10);
$pdf->SetFooterMargin(10);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 25);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 10);

// Report header information
$html = '
<style>
    .info-table { border-collapse: collapse; width: 100%; margin-bottom: 20px; }
    .info-table td { border: 1px solid #ddd; padding: 8px; }
    .info-table .label { background-color: #f2f2f2; font-weight: bold; width: 30%; }
    .data-table { border-collapse: collapse; width: 100%; }
    .data-table th, .data-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    .data-table th { background-color: #4CAF50; color: white; font-weight: bold; }
    .data-table tr:nth-child(even) { background-color: #f2f2f2; }
    .summary { padding: 10px; margin-bottom: 20px; }
    .error-count { color: #721c24; font-weight: bold; font-size: 14px; }
</style>

<div class="summary">
    <p class="error-count">Total Missing Partners: ' . count($partnerData) . '</p>
</div>

<table class="info-table">
    <tr>
        <td class="label">Report Generated</td>
        <td>' . date('Y-m-d H:i:s') . '</td>
    </tr>
    <tr>
        <td class="label">Generated By</td>
        <td>' . htmlspecialchars($_SESSION['admin_name'] ?? 'System') . '</td>
    </tr>
    <tr>
        <td class="label">Source File</td>
        <td>' . htmlspecialchars($fileName) . '</td>
    </tr>
    <tr>
        <td class="label">File Type</td>
        <td>' . htmlspecialchars($sourceType) . '</td>
    </tr>
    <tr>
        <td class="label">Transaction Date</td>
        <td>' . htmlspecialchars($transactionDate) . '</td>
    </tr>
</table>

<h3 style="color: #721c24;">Missing Partner Details</h3>

<table class="data-table">
    <thead>
        <tr>
            <th style="width: 5%;">#</th>
            <th style="width: 25%;">Partner ID</th>
            <th style="width: 60%;">Partner Name</th>
        </tr>
    </thead>
    <tbody>';

if (empty($partnerData)) {
    $html .= '<tr><td colspan="3" style="text-align: center; color: #666;">No missing partners found.</td></tr>';
} else {
    foreach ($partnerData as $index => $partner) {
        $html .= '<tr>
            <td style="width: 5%;">' . ($index + 1) . '</td>
            <td style="width: 25%;"><strong>' . htmlspecialchars($partner['partner_id'] ?? 'N/A') . '</strong></td>
            <td style="width: 60%;">' . htmlspecialchars($partner['partner_name'] ?? 'N/A') . '</td>
        </tr>';
    }
}

$html .= '</tbody>
</table>';

// Write HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Generate filename
$safeFileName = preg_replace('/[^a-zA-Z0-9_-]/', '_', $fileName);
$pdfFileName = 'Partner_Errors_' . $safeFileName . '_' . date('Ymd_His') . '.pdf';

// Output PDF
$pdf->Output($pdfFileName, 'D'); // 'D' = force download
exit();
?>